// v5.0.867
(function(l,h,B,Q,H,I,C,D,V,s,t,ha,x,E,J,R,W,ia,X,q){function Y(a,b,d){if(!a)for(a in p)return p[a];var c=new ja(a);d&&c.za();return p[b||a]=c}function Z(a){for(var b in p)p[W](b)&&a(p[b])}function sa(a,b){return function(){a.call(b)}}function F(a,b,d,c){var e;(e=a.addEventListener)?e.call(a,b,d,t):a.attachEvent(c||"on"+b,d)}function u(a,b){return function(){a(b)}}function K(a,b,d){if(!ta)if("function"==typeof a)a();else if(ua.test(a))"string"!=typeof b&&(d=b,b=0),Y(a,b,d||d===q);else if(/^_/.test(a))S[a]&&
S[a](b,d),delete S[a];else{a=a[x](".");var c;1<a[J]&&(c=a.shift());a=a[0];if("get"==a)return va(c,b);"set"==a?T(c,b,d):"track"==a?$(aa,c,b,d):"event"==a?$(ka,c,b,d):"cancel"==a?wa(c):"noCookies"==a?T(c,1,t):"anonymizeIP"==a?T(c,2,s):"tag"==a?T(c,3,b):"load"==a&&b&&b()}}function T(a,b,d){var c=la[(b+"")[R]()]||b;a?p[a].t(c,d):Z(function(a){a.t(c,d)})}function va(a,b){var d=la[(b+"")[R]()]||b,c;if(a)return p[a].b(d);Z(function(a){c=a.b(d)});return c}function L(a,b){return((a>>1)+(b>>1)<<1)+(a&1)+(b&
1)}function ma(a,b){function d(a){return"expires="+(new I(a)).toGMTString()+";"}var c="path=/;",e=a.b(6);e&&(c+="domain="+e+";");return{N:function(e,f){a.b(1,s)&&(h.cookie=e+"="+f+";"+d(+new I+(b?6E10:6E4))+c)},I:function(b){if(a.b(1,s))return(h.cookie.match("(^|;)\\s*"+b+"=(.*?)(;|$)")||[])[2]||q},ca:function(a){h.cookie=a+"=;"+d(0)+c}}}function $(a,b,d,c){b?a.call(p[b],d,c):Z(function(b){a.call(b,d,c)})}function wa(a){$(function(){this.C()},a)}function ja(a){var b=this;b.c=a;b.Ha=t;var d=[];b.t=
function(a,b){d[a]=b};b.b=function(a,b){return a in d?d[a]:b};var c;b.za=function(){c=C(sa(aa,b),b.b(9,200))};b.C=function(){D(b.g);D(c)}}function aa(a,b){function d(a){m.cb=a}var c=this,e=xa(c,a,b),g=ya(c),f=za(c,!g.J,a!==q),k=Aa(),r=Ba(a),y=ba(),m,h=c.b(5);D(c.g);c.l=0;c.f=t;ca(c);e.ia||(e.ha||B&&"preview"==B.loadPurpose)||k.d.n&&k.d.m&&10>k.d.n&&10>k.d.m||(c.r=y.k,c.p=y.j,m={a:c.c,cs:k.aa,cd:k.D,fl:k.ga,je:k.ja,la:k.ka,sw:k.d.n,sh:k.d.m,dp:k.fa,dm:e.ea,pa:e.oa,pt:e.ya,pr:e.sa,po:e.ta,ri:g.J,ru:g.va,
ui:f.id,re:f.wa,vi:f.Ca,pv:f.ua,lv:f.ma,vw:y.V,vh:y.T,dw:y.H,dh:y.G,st:y.k,sl:y.j,tv:"5.0",un:c.b(3),pp:f.ra,cp:f.ba,ec:h,aip:c.b(2)?1:q},c.t(11,f.id),a===q&&(m.id=c.id),g.L&&(m.oe=g.L.Ea,m.ok=g.L.Ga),r&&(m.c_n=r.Y,m.c_s=r.Z,m.c_m=r.X,m.c_c=r.W,m.c_t=r.$),da&&(v?(m.o_si=v.O,m.o_vi=v.U,m.o_ci=v.F):c.K=s),c.qa=0,d(na(function(a){c.id=a;D(c.g);c.g=C(u(U,c),5E3);F(l,"beforeunload",u(Ca,c))})),ea({M:"pv",h:m}),c.id===q?C(u(Da,c),500):a!==q&&(c.id=q))}function ka(a,b){if("string"==typeof b||"number"==typeof b)b=
{caption:b};b||(b={});b.gs_evt_name=a;U(this,"event",b)}function U(a,b,d){if(!a.xa)if(a.id!==q){if(d===q){var c=ba();d={vw:c.V,vh:c.T,dw:c.H,dh:c.G,st:c.k,sl:c.j,mst:a.r,msl:a.p}}d=d||{};d.a=a.c;d.u=a.b(11);d.i=a.id;d.e=b;d._=H.random();d.tv="5.0";d.et=Ea(a);da&&(a.K&&v)&&(a.K=t,d.o_si=v.O,d.o_vi=v.U,d.o_ci=v.F);d.cb=na(function(){D(a.g);a.xa||(a.g=C(u(U,a),[7E3,12E3][a.qa++]||17500+5E3*H.random()))});ea({M:"ping",h:d})}else{var e=arguments;C(function(){U.apply({},e)},5E3)}}function oa(){var a=l.olark;
a&&a("api.boot.onIdentityReady",function(a,d,c){v={O:a,U:d,F:c}});da=!!a}function ea(a){function b(a){var b=[],c;for(c in a)a[W](c)&&a[c]!==q&&b.push(V(c)+"="+V(a[c]));return b.join("&")}function d(){g&&e.removeChild(g);g=null;fa=(fa+1)%c[J];a.h&&a.h.et&&(a.h.et=0);ea(a)}a.Q===q&&(a.Q=5);if(--a.Q){var c=["data.gosquared.com/"],e=h[ia]("head")[0],g=h[ha]("script"),f=t,k=C(d,1E4),r=a.M+"?"+b(a.h);g.src=("https:"==M().B?"https:":"http:")+"//"+c[fa]+r;g.onload=g.onreadystatechange=function(a){a=this.readyState;
f||a&&"loaded"!=a&&"complete"!=a||(f=s,g&&e.removeChild(g),g=null,D(k))};e.appendChild(g)}}function na(a){var b="_"+Fa++;S[b]=a;return b}function N(a){function b(){var a=e.name;a&&(e.name=a[x](d)[0])}var d=":_GS_:",c;if(N.P)return N.P;var e=l.top;N.P=c={da:function(){b();e.name=(e.name||"")+d+[a,c.uid,c.s]}};try{var g=e.name||"";if(-1!=g[X](d)){var f=g[x](d)[1][x](",");f[0]==a&&(c.uid=f[1]||"",c.s=f[2]||"")}b()}catch(k){e={}}return c}function xa(a,b,d){b=M(M(b).w);return{oa:b.Ba+(a.b(7,s)?b.S:"")[E](/[?&](utm_.*?|gclid)=[^&]*/g,
"")[E](/^&/,"?")+(a.b(8)?b.Aa:""),ya:d!==q?d:h.title,ea:b.R,sa:b.B,ta:b.A||"-",ia:"file:"==b.B,ha:/fb_xd_(bust|fragment)/.test(b.w)}}function Ba(a){a=M(a).S;var b,d,c,e;b=/[?&]([^=]+)=([^&]*)/g;d={};for(e=decodeURIComponent;c=b.exec(a[E](/\+/g," "));d[e(c[1])]=e(c[2]));var g;if(a&&(g=d.utm_campaign))return{Y:g,Z:d.utm_source,X:d.utm_medium,$:d.utm_term,W:d.utm_content}}function Aa(){var a={d:{n:0,m:0},D:"-",ka:(B.language||B.browserLanguage||"-")[R](),ja:+B.javaEnabled(),aa:h.characterSet||h.charSet||
"-",ga:function(a,d){var c,e,g,f,k;if(B&&(c=B.plugins)&&0<(e=c[J]))for(k=0;k<e;k++){if(-1<(f=c[k]).name[X](g=a+" "+d))return c=f.description[x](g+" "),c[1]}else if(c=l.ActiveXObject){try{if(f=(new c((g=a+d+".")+a+d)).GetVariable("$version"))return f=f[x](" ")[1][x](","),f[0]+"."+f[1]+" r"+f[2]}catch(r){}for(k=13;--k;)try{if(f=new c(g+g+k),self.Fa=f&&f.Da,f)return k+".0"}catch(h){}}return"-"}("Shockwave","Flash"),fa:l.devicePixelRatio||1};Q&&(a.d={n:Q.width,m:Q.height},a.D=Q.colorDepth);return a}function ba(){function a(a){return l["inner"+
a]||c&&c[e="client"+a]||d&&d[e]}function b(a){return H.max(d[e="scroll"+a],c[e],d[e="offset"+a],c[e],d[e="client"+a],c[e])}var d=h.body,c=h.documentElement,e;return{V:a("Width"),T:a("Height"),H:b("Width"),G:b("Height"),j:l.pageXOffset||d&&d.scrollLeft||c&&c.scrollLeft||0,k:l.pageYOffset||d&&d.scrollTop||c&&c.scrollTop||0}}function ca(a){D(a.na);a.na=C(u(pa,a),15E3);a.f||(a.f=s,a.o=+new I)}function pa(a){a.f&&(a.f=t,a.l=(a.l||0)+ +new I-a.o)}function Ea(a){var b=a.l,d=+new I;a.f&&(b+=d-a.o,a.o=d);
a.l=0;return b}function Ga(a){ca(a);var b=ba();b.k>a.r&&(a.r=b.k);b.j>a.p&&(a.p=b.j)}function Da(a){var b=u(ca,a);F(h,"mousemove",b);F(h,"keydown",b);F(l,"scroll",u(Ga,a));F(h,"focus",b,"focusin");F(h,"blur",u(pa,a),"focusout")}function ya(a){a=a.b(10,h.referrer);var b;!a||/^(chrome|about|file):/.test(a)||/^\[.*\]$/.test(a)?a="-":b=M(a).R[X](h.domain);return{J:+(0<=b&&8>=b),va:a}}function Ca(a){var b=ma(a);a.b(1,s)?b.N("gs_p_"+a.c,a.id):(b=N(a.c),b.s=a.id,b.da())}function za(a,b,d){var c=ma(a,1),
e=N(a.c),g=c.I("gs_u_"+a.c)||e.uid,f=1,k=1,r=(g||"")[x](":"),h,m=s,n=0,l;g&&/^[0-9\:]*$/.test(g)?(g=r[0],f=((r[1]||2019)-2019)/548+ +!!b,k=((r[2]||4621)-4621)/379+1,n=(r[3]||0)/1E3):(m=t,g=0|2147483647*H.random());c.N("gs_u_"+a.c,e.uid=[g,2019+548*f,4621+379*k,+new I].join(":"));b=c.I("gs_p_"+a.c)||e.s;b!==q&&(l=b,c.ca("gs_p_"+a.c));d&&(l=a.id);if((a=a.b(4))&&"object"==typeof a){h=[];for(var p in a)a[W](p)&&h.push(p+"="+("gravatar"==p?Ha(a[p][E](/^\s+|\s+$/g,"")[R]()):a[p]));h=h.join("|")}return{id:+g,
Ca:f,ua:k,ma:~~n,wa:m,ra:l,ba:h}}var O,G=l._gs||(O=s,function(){G.q.push(arguments)});G.q=G.q||[];if(!G.v){var ua=/^GSN-.*-.$/,p={},w=l.GoSquared;if(w){var n,P;for(n in w)P=w[n],"acct"==n?(Y(P,"default",s),G(function(){function a(a){b[a.shift()].apply(b,a)}var b=w.DefaultTracker=p["default"];if(n=w.q)for(;P=n.shift();)a(P);w.q={push:a};(n=w.load)&&n(b)})):"load"!=n&&"q"!=n&&G("set",n,P);n=ja.prototype;n.TrackView=aa;n.TrackEvent=ka;n.Cancel=function(){this.C()};w.Tracker=Y;w.Cancel=u(K,"cancel")}for(var ta,
la={usecookies:1,anonymiseip:2,visitorname:3,username:3,statuscode:5,cookiedomain:6,trackparams:7,trackhash:8,trackdelay:9,referrer:10,visitorid:11},qa=[],z=0;64>z;)qa[z]=0|4294967296*H.abs(H.sin(++z));var Ha=function(a){var b,d,c,e,g=[];a=unescape(V(a));for(var f=a[J],k=[b=1732584193,d=-271733879,~b,~d],h=0;h<=f;)g[h>>2]|=(a.charCodeAt(h)||128)<<8*(h++%4);g[a=16*(f+8>>6)+14]=8*f;for(h=0;h<a;h+=16){f=k;for(e=0;64>e;)f=[c=f[3],L(b=f[1],(c=L(L(f[0],[b&(d=f[2])|~b&c,c&b|~c&d,b^d^c,d^(b|~c)][f=e>>4]),
L(qa[e],g[[e,5*e+1,3*e+5,7*e][f]%16+h])))<<(f=[7,12,17,22,5,9,14,20,4,11,16,23,6,10,15,21][4*f+e++%4])|c>>>32-f),b,d];for(e=4;e;)k[--e]=L(k[e],f[e])}for(a="";32>e;)a+=(k[e>>3]>>4*(1^e++&7)&15).toString(16);return a},da=t,v,fa=0,S={},Fa=0,A=h[ha]("a"),M=function(a){a===q&&(a=location.href);A.href=a;a={Ba:A.pathname[E](/^([^\/]|$)/,"/$1"),Aa:A.hash[E](/^#$/,""),B:A.protocol[E](/^:$/,"")||location.protocol,R:A.hostname||location.hostname,w:A.href,S:A.search,A:A.port};a.w.match(":"+a.A)||(a.A="");return a},
ga=G.q;l._gs=K;for(K.v="5.0";z=ga.shift();)K.apply({},z);if(O){O=h[ia]("script");for(var ga=O[J],z=0,ra;z<ga;)if(ra=O[z++].getAttribute("data-gs")){K(ra);break}}oa();F(l,"load",oa)}})(window,document,navigator||{},screen,Math,Date,setTimeout,clearTimeout,encodeURIComponent,1,0,"createElement","split","replace","length","toLowerCase","hasOwnProperty","getElementsByTagName","indexOf");
